services:
  app:
    build:
      context: .
      target: production
    container_name: job_hub_backend
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - BACKEND_IP=0.0.0.0
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    container_name: job_hub_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

volumes:
  redis_data:

networks:
  app_network:
    driver: bridge
